import "dotenv/config";import express from "express";import cors from "cors";import helmet from "helmet";import rateLimit from "express-rate-limit";import cookieParser from "cookie-parser";import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import mongoose,{Schema}from"mongoose";import{createClient}from"redis";import crypto from"crypto";
const env={PORT:Number(process.env.PORT||4000),MONGODB_URI:process.env.MONGODB_URI||"mongodb://localhost:27017/solosync",REDIS_URL:process.env.REDIS_URL||"redis://localhost:6379",JWT_SECRET:process.env.JWT_SECRET||"change-me",FRONTEND_ORIGIN:process.env.FRONTEND_ORIGIN||"http://localhost:5173",NODE_ENV:process.env.NODE_ENV||"development"};if(env.NODE_ENV==="production"&&env.JWT_SECRET==="change-me")throw Error("JWT_SECRET must be configured");
const UserSchema=new Schema({email:{type:String,required:true,unique:true,lowercase:true,trim:true},passwordHash:{type:String,required:true}},{timestamps:true});const User=mongoose.model("User",UserSchema);const redis=createClient({url:env.REDIS_URL});
const app=express();app.use(helmet());app.use(cors({origin:env.FRONTEND_ORIGIN,credentials:true}));app.use(express.json({limit:"1mb"}));app.use(cookieParser());app.use("/api/auth",rateLimit({windowMs:60_000,max:20,standardHeaders:true,legacyHeaders:false}));
const cookieOpts={httpOnly:true,secure:env.NODE_ENV==="production",sameSite:"lax" as const,path:"/"};function signAccess(id:string){return jwt.sign({sub:id,type:"access"},env.JWT_SECRET,{expiresIn:"15m"})}function signRefresh(id:string){return jwt.sign({sub:id,type:"refresh",jti:crypto.randomUUID()},env.JWT_SECRET,{expiresIn:"7d"})}function userView(u:any){return{id:String(u._id),email:u.email,createdAt:u.createdAt}}
app.get("/health",(_,res)=>res.json({status:"ok"}));app.get("/ready",async(_,res)=>{try{await mongoose.connection.db?.command({ping:1});await redis.ping();res.json({status:"ready"})}catch{res.status(503).json({status:"not_ready"})}});
app.post("/api/auth/register",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return res.status(400).json({message:"Valid email and password of at least 8 characters are required"});if(await User.exists({email}))return res.status(409).json({message:"Account already exists"});const u=await User.create({email,passwordHash:await bcrypt.hash(password,12)});const refresh=signRefresh(String(u._id));await redis.setEx("session:"+crypto.createHash("sha256").update(refresh).digest("hex"),7*24*3600,String(u._id));res.cookie("access_token",signAccess(String(u._id)),{...cookieOpts,maxAge:15*60*1000});res.cookie("refresh_token",refresh,{...cookieOpts,maxAge:7*24*3600*1000});res.status(201).json({user:userView(u)})}catch(e){res.status(500).json({message:"Unable to create account"})}});
app.post("/api/auth/login",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");const u=await User.findOne({email});if(!u||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({message:"Invalid email or password"});const refresh=signRefresh(String(u._id));await redis.setEx("session:"+crypto.createHash("sha256").update(refresh).digest("hex"),7*24*3600,String(u._id));res.cookie("access_token",signAccess(String(u._id)),{...cookieOpts,maxAge:15*60*1000});res.cookie("refresh_token",refresh,{...cookieOpts,maxAge:7*24*3600*1000});res.json({user:userView(u)})});
app.post("/api/auth/refresh",async(req,res)=>{try{const token=req.cookies.refresh_token;if(!token)throw Error();const p:any=jwt.verify(token,env.JWT_SECRET);if(p.type!=="refresh")throw Error();const key="session:"+crypto.createHash("sha256").update(token).digest("hex");if(!(await redis.get(key)))throw Error();res.cookie("access_token",signAccess(p.sub),{...cookieOpts,maxAge:15*60*1000});res.json({ok:true})}catch{res.status(401).json({message:"Refresh session expired"})}});
app.post("/api/auth/logout",async(req,res)=>{const token=req.cookies.refresh_token;if(token)await redis.del("session:"+crypto.createHash("sha256").update(token).digest("hex"));res.clearCookie("access_token",cookieOpts);res.clearCookie("refresh_token",cookieOpts);res.status(204).end()});
app.get("/api/auth/me",async(req,res)=>{try{const token=req.cookies.access_token;if(!token)throw Error();const p:any=jwt.verify(token,env.JWT_SECRET);if(p.type!=="access")throw Error();const u=await User.findById(p.sub).select("_id email createdAt");if(!u)throw Error();res.json({user:userView(u)})}catch{res.status(401).json({message:"Not authenticated"})}});
async function start(){await mongoose.connect(env.MONGODB_URI);await redis.connect();app.listen(env.PORT,"0.0.0.0",()=>console.log("SoloSync API listening on "+env.PORT))}start().catch(e=>{console.error(e);process.exit(1)});